/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import DAO.HoaDonChiTietDAO;
import DAO.hdct1DAO;
import ENTITY.ChiTietHoaDon;
import ENTITY.HoaDon;
import java.sql.*;
import java.text.NumberFormat;

import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen vu
 */
public class CTHoaDonForm extends javax.swing.JDialog {

    DefaultTableModel tblModel;
    Connection cnn;
    Statement st;
    HoaDonChiTietDAO dao1 = new HoaDonChiTietDAO();

    /**
     * Creates new form
     */
    public CTHoaDonForm() {

        initComponents();

        setLocationRelativeTo(null);

        try {

            String url = "jdbc:sqlserver://localhost:1433;databaseName=duan1;encrypt=true;trustServerCertificate=true;";
            String user = "edu";
            String pass = "123";
            cnn = DriverManager.getConnection(url, user, pass);
            fillTable();
        } catch (SQLException ex) {
            System.out.println("loi kn");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        btntim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hoá Đơn Chi Tiết");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 728, 34));

        txtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaActionPerformed(evt);
            }
        });
        getContentPane().add(txtma, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, 568, 25));

        btntim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntim.setText("Tìm");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });
        getContentPane().add(btntim, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 41, 118, -1));

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Tên Nhân Viên", "Tên Khách Hàng", "Tổng Tiền", "Ngày Lập Hóa Đơn"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDanhSachMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, 710, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaActionPerformed

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_btntimActionPerformed

    private void tblDanhSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMousePressed
        // TODO add your handling code here:

//      int npp=1;

		
	// tạo 1 NumberFormat để định dạng tiền tệ theo tiêu chuẩn của Việt Nam
	// đơn vị tiền tệ của Việt Nam là đồng
	Locale localeVN = new Locale("vi", "VN");
	NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
	
        try {
            int i = tblDanhSach.getSelectedRow();
            String mahd = (String) tblDanhSach.getValueAt(i, 0);
            List<ChiTietHoaDon> list = dao1.selectByKeyword(mahd);
            String str3 = "Hóa Đơn Chi Tiết", str = "";
            int str1 = 0;
            long str2 = 0;
            for (ChiTietHoaDon ct : list) {

                str+= ct.getTenSP();
                str1+= ct.getSoLuong();
                str2+= ct.getTongtien();
            }
            JOptionPane.showMessageDialog(null, "Tổng Sản Phẩm Đã :\t " 
                    + str1 
                    + "\n" + "Sản Phẩm:\n"
                    + str + "Tổng Giá Tiền:\t" 
                    +currencyVN.format(str2),str3,-1);
          
      
        } catch (Exception e) {
            System.out.println(e);;
        }


    }//GEN-LAST:event_tblDanhSachMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTHoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTHoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTHoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTHoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTHoaDonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtma;
    // End of variables declaration//GEN-END:variables
     hdct1DAO dao = new hdct1DAO();

    void fillTable() {
        DefaultTableModel modelct = (DefaultTableModel) tblDanhSach.getModel();
        modelct.setRowCount(0);
        try {

            String keyword = txtma.getText();
            List<HoaDon> list = dao.selectByKeyword(keyword);
            for (HoaDon ct : list) {
                Object[] row = {
                    ct.getMahd(),
                    ct.getTennv(),
                    ct.getTenkh(),
                    ct.getThanhtien(),
                    ct.getNgaymua()
                };
                modelct.addRow(row);
            }

        } catch (Exception e) {
            System.out.println(e);;
        }
    }
}
